before_script:
    - echo '*** Install packages needed by aravis ***'
    - . /etc/os-release
    - >
      if [ -x "/opt/rh/devtoolset-7/enable" ]; then
        source /opt/rh/devtoolset-7/enable
      fi
    - >
      if [ "$ID" = "centos" -o "$ID" = "almalinux" -o "$ID" = "rhel" ]; then
        yum install -y glib2-devel
      elif [ "$ID" = "ubuntu" ]; then
        apt-get update
        apt-get install -y intltool libglib2.0-dev
      fi

include:
  - project: karabo/gitlabci
    file: .cpp-ci.yml
    ref: main
  - project: karabo/gitlabci
    file: .cpp-package.yml
    ref: main
  - project: karabo/gitlabci
    file: .mirror-device.yml
    ref: main
